development:
  adapter: postgresql
  encoding: unicode
  database: first_app_development
  pool: 5
  username: postgres
  password: sad2121


test:
  adapter: postgresql
  encoding: unicode
  database: first_app_test
  pool: 5
  username: postgres
  password: sad2121


production:
  adapter: postgresql
  encoding: unicode
  database: first_app_production
  pool: 5
  username: demo_app
  password:
